//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebRedSocialProyectos.wsProject {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSProjecManagerPortBinding", Namespace="http://WebServices/")]
    public partial class WSProjecManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listaPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearTareaIndOperationCompleted;
        
        private System.Threading.SendOrPostCallback getidTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarConocimientoTareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback situacionTareaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSProjecManager() {
            this.Url = global::WebRedSocialProyectos.Properties.Settings.Default.WebRedSocialProyectos_wsProject_WSProjecManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listaPagoCompletedEventHandler listaPagoCompleted;
        
        /// <remarks/>
        public event crearTareaIndCompletedEventHandler crearTareaIndCompleted;
        
        /// <remarks/>
        public event getidTareaCompletedEventHandler getidTareaCompleted;
        
        /// <remarks/>
        public event RegistrarConocimientoTareaCompletedEventHandler RegistrarConocimientoTareaCompleted;
        
        /// <remarks/>
        public event situacionTareaCompletedEventHandler situacionTareaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pago[] listaPago() {
            object[] results = this.Invoke("listaPago", new object[0]);
            return ((pago[])(results[0]));
        }
        
        /// <remarks/>
        public void listaPagoAsync() {
            this.listaPagoAsync(null);
        }
        
        /// <remarks/>
        public void listaPagoAsync(object userState) {
            if ((this.listaPagoOperationCompleted == null)) {
                this.listaPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaPagoOperationCompleted);
            }
            this.InvokeAsync("listaPago", new object[0], this.listaPagoOperationCompleted, userState);
        }
        
        private void OnlistaPagoOperationCompleted(object arg) {
            if ((this.listaPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaPagoCompleted(this, new listaPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool crearTareaInd([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string texto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechain, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int duracion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int cant, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float pago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idusuario) {
            object[] results = this.Invoke("crearTareaInd", new object[] {
                        nombre,
                        texto,
                        fechain,
                        duracion,
                        cant,
                        pago,
                        idusuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void crearTareaIndAsync(string nombre, string texto, string fechain, int duracion, int cant, float pago, int idusuario) {
            this.crearTareaIndAsync(nombre, texto, fechain, duracion, cant, pago, idusuario, null);
        }
        
        /// <remarks/>
        public void crearTareaIndAsync(string nombre, string texto, string fechain, int duracion, int cant, float pago, int idusuario, object userState) {
            if ((this.crearTareaIndOperationCompleted == null)) {
                this.crearTareaIndOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearTareaIndOperationCompleted);
            }
            this.InvokeAsync("crearTareaInd", new object[] {
                        nombre,
                        texto,
                        fechain,
                        duracion,
                        cant,
                        pago,
                        idusuario}, this.crearTareaIndOperationCompleted, userState);
        }
        
        private void OncrearTareaIndOperationCompleted(object arg) {
            if ((this.crearTareaIndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearTareaIndCompleted(this, new crearTareaIndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getidTarea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string desc) {
            object[] results = this.Invoke("getidTarea", new object[] {
                        nombre,
                        desc});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getidTareaAsync(string nombre, string desc) {
            this.getidTareaAsync(nombre, desc, null);
        }
        
        /// <remarks/>
        public void getidTareaAsync(string nombre, string desc, object userState) {
            if ((this.getidTareaOperationCompleted == null)) {
                this.getidTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetidTareaOperationCompleted);
            }
            this.InvokeAsync("getidTarea", new object[] {
                        nombre,
                        desc}, this.getidTareaOperationCompleted, userState);
        }
        
        private void OngetidTareaOperationCompleted(object arg) {
            if ((this.getidTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getidTareaCompleted(this, new getidTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool RegistrarConocimientoTarea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idtarea, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idconocimiento) {
            object[] results = this.Invoke("RegistrarConocimientoTarea", new object[] {
                        idtarea,
                        idconocimiento});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarConocimientoTareaAsync(int idtarea, int idconocimiento) {
            this.RegistrarConocimientoTareaAsync(idtarea, idconocimiento, null);
        }
        
        /// <remarks/>
        public void RegistrarConocimientoTareaAsync(int idtarea, int idconocimiento, object userState) {
            if ((this.RegistrarConocimientoTareaOperationCompleted == null)) {
                this.RegistrarConocimientoTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarConocimientoTareaOperationCompleted);
            }
            this.InvokeAsync("RegistrarConocimientoTarea", new object[] {
                        idtarea,
                        idconocimiento}, this.RegistrarConocimientoTareaOperationCompleted, userState);
        }
        
        private void OnRegistrarConocimientoTareaOperationCompleted(object arg) {
            if ((this.RegistrarConocimientoTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarConocimientoTareaCompleted(this, new RegistrarConocimientoTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool situacionTarea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idsituacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idtarea) {
            object[] results = this.Invoke("situacionTarea", new object[] {
                        idsituacion,
                        idtarea});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void situacionTareaAsync(int idsituacion, int idtarea) {
            this.situacionTareaAsync(idsituacion, idtarea, null);
        }
        
        /// <remarks/>
        public void situacionTareaAsync(int idsituacion, int idtarea, object userState) {
            if ((this.situacionTareaOperationCompleted == null)) {
                this.situacionTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsituacionTareaOperationCompleted);
            }
            this.InvokeAsync("situacionTarea", new object[] {
                        idsituacion,
                        idtarea}, this.situacionTareaOperationCompleted, userState);
        }
        
        private void OnsituacionTareaOperationCompleted(object arg) {
            if ((this.situacionTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.situacionTareaCompleted(this, new situacionTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebServices/")]
    public partial class pago {
        
        private int idpagoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idpago {
            get {
                return this.idpagoField;
            }
            set {
                this.idpagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void listaPagoCompletedEventHandler(object sender, listaPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public pago[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((pago[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void crearTareaIndCompletedEventHandler(object sender, crearTareaIndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearTareaIndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearTareaIndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getidTareaCompletedEventHandler(object sender, getidTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getidTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getidTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RegistrarConocimientoTareaCompletedEventHandler(object sender, RegistrarConocimientoTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarConocimientoTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarConocimientoTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void situacionTareaCompletedEventHandler(object sender, situacionTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class situacionTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal situacionTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591